### ISSUE TITLE
Windows Hello is gone

### ISSUE THREAD

**Issue by atropos112** [builtbybel/bloatbox#14]
After asking it to remove edge, paint and other features that had nothing to do with windows hello (or start menu) i notice my start menu is reset to default and my Windows Hello no longer works. Any idea how to get Windows Hello back?

**Comment by Belim** [comment]
if you remove all apps of course, all tiles will disappear from the start menu. this can be called reset.
You coud use the community package and run the "Reinstall all built-in apps" script to get them all back

Info and how-to  here
https://github.com/builtbybel/bloatbox#community-package

**Comment by atropos112** [comment]
I think i may have not explained well enough, i mean all apps disappeared from start including ones which had nothing to do with the removal and that was after i clicked "no" to reseting the start menu. 

I've tried Reinstalling all built-in apps the computer did not see a "Windows hello" driver anymore and when searching for it/restarting pc and other methods i found online the PC had no ability to use windows hello because windows hello had no access to the camera, after enabling it to be used for all the apps the issue persisted. I ended up formating the whole PC because Windows Hello is a feature i found valuable and wish i was told this was a thing i was going to lose.

**Comment by Belim** [comment]
well, you've runned the optional feature [Windows10Debloater.ps1](https://github.com/Sycnex/Windows10Debloater)

Bloatbox doesn't touch Windows hello as this isnt an UWP app and i'm not aware that the powerhsell script from the optional feature does this in any way. here is the content of the script file https://github.com/Sycnex/Windows10Debloater/blob/master/Windows10Debloater.ps1

**Comment by atropos112** [comment]
Yes i did use to optional feature, to be very honest I read throguh it as a precausion and it seems clear with what it does, I do not know what caused the Windows Hello to go, all i know is that after i did the debloat i reseted computer right after and it was gone and before that all i did is browse github, perhaps certain telemetry causes it to stop?

**Comment by Belim** [comment]
>  perhaps certain telemetry causes it to stop?

I'm really not sure. A problem has also been opened in the repo of Windows1Debloater.ps1
https://github.com/Sycnex/Windows10Debloater/issues/203
