### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [builtbybel/bloatbox#15]
It is sad that the application is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, or any other service. It is completely free for open source projects.)

**Comment by Belim** [comment]
https://github.com/builtbybel/privatezilla/issues/12

**Comment by Belim** [comment]
Its localizable now
https://github.com/builtbybel/bloatbox/releases/tag/0.20.0
