### ISSUE TITLE
Removes Start menu pins when told not to

### ISSUE THREAD

**Issue by technoabyss** [builtbybel/bloatbox#16]
While running the "community edition", saying "No" when asked if I want to remove my Start menu pins leaves my start menu looking like this when I restart:

![image](https://user-images.githubusercontent.com/52284719/91660896-09620900-eac8-11ea-9bb3-299e7aa0a1b1.png)

**Comment by Belim** [comment]
Please use the community package from my repo https://github.com/builtbybel/bloatbox#community-package
You will find here another script for unpinning tiles which get its job done right.

The script above can't do that, but it's not from me either https://github.com/Sycnex/Windows10Debloater
