### ISSUE TITLE
Does Bloatbox Support Windows 11?

### ISSUE THREAD

**Issue by WarningU2** [builtbybel/bloatbox#44]
From researching on majorgeeks it appears bloatbox will only support Windows 10?    Please confirm it does / does not support Windows 11.   Thanks

**Comment by Nico04** [comment]
Maybe this is the answer? (same dev)
https://github.com/builtbybel/ThisIsWin11

**Comment by WarningU2** [comment]
Thanks Nico04 ... looks promising.  Concerned the repository has been archived.  Makes me wonder about support going forward.   But thanks for sharing.

**Comment by Nico04** [comment]
Well you're right, I missed that. However : 

> BloatyNosy is the replacement app for the [ThisIsWin11](https://github.com/builtbybel/ThisIsWin11) tool which is no longer supported.

https://www.builtbybel.com/apps/bloatynosy

To be tested though

**Comment by WarningU2** [comment]
Thanks ... I think I'll wait until it is released proper.   Quite surprised actually at the amount of MS bloatware they (MS) lets you uninstall.

**Comment by WarningU2** [comment]
Closing
