### ISSUE TITLE
Duplicate files in repository

### ISSUE THREAD

**Issue by gregsskyles** [builtbybel/bloatbox#5]
In `src/Bloatbox/Resources/` you have both `Bloatbox.txt` and `bloatbox.txt` which differ only in the initial upper or lower case 'b'. The files are identical at the moment; however if they end up differing in the future you might have a problem. For example, a `git clone` to a Windows system will cause git to pick just one of them to keep.

**Comment by Belim** [comment]
Thanks to such direct feedback. I wasn't aware that git handled it this way.
I have removed the duplicate `bloatbox.txt`. I have indeed released this one in the last release as `Bloatbox.txt`

**Comment by gregsskyles** [comment]
No worries, mate! (As we say down here in Australia)
Git, having been developed on Linux, respects the case of (the characters in) file names, which most of us who spend most of our time on Windows tend to forget. I know I do.
Thanks for fixing it; I think it will help reduce issues in the future, or at least, confusion in the present.
