### ISSUE TITLE
All-Users options

### ISSUE THREAD

**Issue by DGSephiro** [builtbybel/bloatbox#7]
Wondering if this can be updated to apply for all users?
So far, I am really enjoying this tool (just found it a few days ago) but I've noticed when I log in with another user account, most of what was scrubbed is still there in Start Menu, Pinned items, etc. 

This is the start menu of a second local account on a fresh Windows 10 install. The administrator account I ran it from looks great!

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6360187/88411749-193a4f00-cd9e-11ea-8451-a5e0342b31a0.png)

**Comment by Belim** [comment]
It could be done, but I have a bad taste in it. I had some bad experience with it when i added this function to one of my other apps https://github.com/builtbybel/sharpapp and it didn't work properly either

Some users had also confirmed this https://github.com/builtbybel/sharpapp/issues/15

**Comment by DGSephiro** [comment]
Fair enough.  Its just one of the things I miss about Windows 7, easy start menu management and no bloatware.  :(
